language: ruby
notifications:
  email: false
rvm:
  - 1.9.3
  - jruby-19mode
env: DISPLAY=:99.0 RAILS_ENV=test
before_script:
  - psql -c 'create database madek_test;' -U postgres
  - psql -c 'create database madek_personas;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/database_pg.yml config/database.yml"
  - "rm -f tmp/*.mysql"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install libimage-exiftool-perl imagemagick wget ffmpeg zip unzip memcached"
bundler_args: --without development
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rake madek:test:travis
