# Once you have a live service running, all new keys
#       SHOULD BE ADDED TO THE END OF THE FILE!
#
#                   If you do not, 
#           YOU WILL BREAK THE METADATA 
#       in interesting and painful-to-fix ways.
#
#              You have been WARNED!!!
- 
  label: identifier
-
  label: urn
- 
  label: title
- 
  label: subtitle
- 
  label: author
  object_type: Person
- 
  label: additional authors
  object_type: Person
- 
  label: institutional affiliation
  object_type: MetaDepartment
- 
  label: portrayed object dates
- 
  label: keywords
  object_type: Keyword
- 
  label: classification
- 
  label: portrayed object location
- 
  label: portrayed object city
-
  label: portrayed object state
-
  label: portrayed object country
- 
  label: portrayed object country code
  object_type: MetaCountry
- 
  label: portrayed person
- 
  label: portrayed institution
-
  label: other creative participants
-
  label: other document participants
- 
  label: participating institution
- 
  label: patron
- 
  label: academic year
  object_type: MetaTerm
  meta_terms: 
  -
    de_CH: 1. Semester Bachelor
  -
    de_CH: 2. Semester Bachelor
  -
    de_CH: 3. Semester Bachelor
  -
    de_CH: 4. Semester Bachelor
  -
    de_CH: 5. Semester Bachelor
  -
    de_CH: 6. Semester Bachelor
  -
    de_CH: 1. Semester Master
  -
    de_CH: 2. Semester Master
  -
    de_CH: 3. Semester Master
  -
    de_CH: MAS (Master of Advanced Studies)
  -
    de_CH: DAS (Diploma of Advanced Studies)
  -
    de_CH: CAS (Certificate of Advanced Studies CAS)
  -
    de_CH: Doktoratsprogramm
  -
    de_CH: sonstiges
- 
  label: project leader
- 
  label: project type
  object_type: MetaTerm
  meta_terms: 
  -
    de_CH: Abschlussarbeit
  -
    de_CH: Ausstellung
  -
    de_CH: Dokumentation
  -
    de_CH: Forschung
  -
    de_CH: Lehre
  -
    de_CH: Lehrmittel
  -
    de_CH: Recherche
- 
  label: description
- 
  label: short description
- 
  label: public caption
- 
  label: remark
- 
  label: hyperlinks
- 
  label: tags
- 
  label: type
  object_type: MetaTerm
  meta_terms: 
  -
    de_CH: Architektur
  -
    de_CH: Design
  -
    de_CH: Film
  -
    de_CH: Fotografie
  -
    de_CH: Tanz
  -
    de_CH: Theater
  -
    de_CH: Kunst
  -
    de_CH: Literatur
  -
    de_CH: Mediale Künste
  -
    de_CH: Musik
- 
  label: scene
- 
  label: subject code
- 
  label: coverage
- 
  label: language
- 
  label: relation
- 
  label: creator
  object_type: Person
- 
  label: creator address
- 
  label: creator city
- 
  label: creator state
- 
  label: creator postal code
- 
  label: creator country
- 
  label: creator work telephone
- 
  label: creator work email
- 
  label: creator work url
- 
  label: creator position
- 
  label: source
-
  label: source side
-
  label: source image
-
  label: source plate
-
  label: source isbn
- 
  label: copyright notice
- 
  label: copyright status
  object_type: Copyright
- 
  label: copyright usage
  is_dynamic: true
- 
  label: copyright url
  is_dynamic: true
- 
  label: provider
- 
  label: portrayed object dimensions
- 
  label: portrayed object materials
- 
  label: rating
- 
  label: uploaded by
  object_type: Person
  is_dynamic: true
- 
  label: uploaded at
  object_type: Date
  is_dynamic: true
- 
  label: description author
  object_type: Person
- 
  label: publisher
- 
  label: format
- 
  label: date created
- 
  label: transmission reference
- 
  label: objectnumber
- 
  label: objectname
- 
  label: public access
  is_dynamic: true
- 
  label: media type
  is_dynamic: true
