---
- 
    meta_key: author
    meta_field: 
      is_required: true
    key_map: XMP-madek:Author
    meta_context: io_interface
- 
    meta_key: additional authors
    meta_field: 
      is_required: false
    key_map: XMP-madek:AdditionalAuthors
    key_map_type: Array
    meta_context: io_interface
- 
    meta_key: copyright notice
    meta_field: 
      is_required: true
    key_map: XMP-dc:Rights
    meta_context: io_interface
- 
    meta_key: copyright status
    meta_field: 
      is_required: false
    key_map: XMP-xmpRights:Marked
    meta_context: io_interface
- 
    meta_key: copyright usage
    meta_field: 
      is_required: false
    key_map: XMP-xmpRights:UsageTerms
    meta_context: io_interface
- 
    meta_key: copyright url
    meta_field: 
      is_required: false
    key_map: XMP-xmpRights:WebStatement
    meta_context: io_interface
- 
    meta_key: description author
    meta_field: 
      is_required: true
    key_map: XMP-photoshop:CaptionWriter
    meta_context: io_interface
- 
    meta_key: coverage
    meta_field: 
      is_required: true
      length_max: 255
      length_min: 2
    key_map: XMP-madek:Coverage
    meta_context: io_interface
- 
    meta_key: creator
    meta_field: 
      is_required: true
    key_map: XMP-dc:Creator
    meta_context: io_interface
- 
    meta_key: creator position
    meta_field: 
      is_required: true
    key_map: XMP-photoshop:AuthorsPosition
    meta_context: io_interface
- 
    meta_key: creator address
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorAddress
    meta_context: io_interface
- 
    meta_key: creator city
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorCity
    meta_context: io_interface
- 
    meta_key: creator state
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorRegion
    meta_context: io_interface
- 
    meta_key: creator country
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorCountry
    meta_context: io_interface
- 
    meta_key: creator postal code
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorPostalCode
    meta_context: io_interface
- 
    meta_key: creator work telephone
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorWorkTelephone
    meta_context: io_interface
- 
    meta_key: creator work email
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorWorkEmail
    meta_context: io_interface
- 
    meta_key: creator work url
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CreatorWorkURL
    meta_context: io_interface
- 
    meta_key: description
    meta_field: 
      is_required: true
      length_max: 4096
      length_min: 1
    key_map: XMP-dc:Description
    meta_context: io_interface
- 
    meta_key: format
    meta_field: 
      is_required: true
    key_map: XMP-madek:Format
    meta_context: io_interface
- 
    meta_key: hyperlinks
    meta_field: 
      is_required: false
    key_map: XMP-madek:Hyperlinks
    meta_context: io_interface
- 
    meta_key: institutional affiliation
    meta_field: 
      is_required: false
    key_map: XMP-madek:InstitutionalAffiliation
    meta_context: io_interface
- 
    meta_key: identifier
    meta_field: 
      is_required: true
      length_max: 255
      length_min: 1
    key_map: XMP-dc:Identifier
    meta_context: io_interface
- 
    meta_key: keywords
    meta_field: 
      is_required: true
    key_map: XMP-dc:Subject
    key_map_type: Array
    meta_context: io_interface
- 
    meta_key: language
    meta_field: 
      is_required: true
    key_map: XMP-madek:Language
    meta_context: io_interface
- 
    meta_key: other creative participants
    meta_field: 
      length_max: 255
      length_min: 1
    key_map: XMP-madek:OtherCreativeParticipants
    meta_context: io_interface
- 
    meta_key: other document participants
    meta_field: 
      length_max: 255
      length_min: 1
    key_map: XMP-madek:OtherDocumentParticipants
    meta_context: io_interface
- 
    meta_key: patron
    meta_field: 
      is_required: false
    key_map: XMP-madek:patron
    meta_context: io_interface
- 
    meta_key: portrayed person
    meta_field: 
      is_required: false
    key_map: XMP-madek:PortrayedPerson
    meta_context: io_interface
- 
    meta_key: portrayed institution
    meta_field: 
      is_required: false
    key_map: XMP-madek:PortrayedInstitution
    meta_context: io_interface
- 
    meta_key: project leader
    meta_field: 
      is_required: false
    key_map: XMP-madek:ProjectLeader
    meta_context: io_interface
- 
    meta_key: public caption
    meta_field: 
      is_required: false
    key_map: XMP-madek:PublicCaption
    meta_context: io_interface
- 
    meta_key: portrayed object dimensions
    meta_field: 
      is_required: false
    key_map: XMP-madek:PortrayedObjectDimensions
    meta_context: io_interface
- 
    meta_key: portrayed object materials
    meta_field: 
      is_required: false
    key_map: XMP-madek:PortrayedObjectMaterials
    meta_context: io_interface
- 
    meta_key: portrayed object dates
    meta_field: 
      is_required: true
      length_max: 255
    key_map: XMP-madek:PortrayedObjectDates
    meta_context: io_interface
- 
    meta_key: portrayed object country code
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:CountryCode
    meta_context: io_interface
- 
    meta_key: portrayed object location
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:Location
    meta_context: io_interface
- 
    meta_key: portrayed object city
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-photoshop:City
    meta_context: io_interface
- 
    meta_key: portrayed object state
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-photoshop:State
    meta_context: io_interface
- 
    meta_key: portrayed object country
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-photoshop:Country
    meta_context: io_interface
- 
    meta_key: provider
    meta_field: 
      is_required: true
    key_map: XMP-photoshop:Credit
    meta_context: io_interface
- 
    meta_key: rating
    meta_field: 
      is_required: true
    key_map: XMP-xmp:Rating
    meta_context: io_interface
- 
    meta_key: relation
    meta_field: 
      is_required: true
    key_map: XMP-madek:Relation
    meta_context: io_interface
- 
    meta_key: remark
    meta_field: 
      is_required: false
    key_map: XMP-madek:Remark
    meta_context: io_interface
- 
    meta_key: source
    meta_field: 
      is_required: true
    key_map: XMP-photoshop:Source
    meta_context: io_interface
- 
    meta_key: source image
    meta_field: 
      is_required: false
    key_map: XMP-madek:SourceImage
    meta_context: io_interface
- 
    meta_key: source plate
    meta_field: 
      is_required: false
    key_map: XMP-madek:SourcePlate
    meta_context: io_interface
- 
    meta_key: source side
    meta_field: 
      is_required: false
    key_map: XMP-madek:SourceSide
    meta_context: io_interface
- 
    meta_key: source isbn
    meta_field: 
      is_required: false
    key_map: XMP-madek:SourceIsbn
    meta_context: io_interface
- 
    meta_key: scene
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:Scene
    meta_context: io_interface
- 
    meta_key: subject code
    meta_field: 
      is_required: true
      length_max: 32
      length_min: 1
    key_map: XMP-iptcCore:SubjectCode
    meta_context: io_interface
- 
    meta_key: short description
    meta_field: 
      is_required: false
    key_map: XMP-madek:ShortDescription
    meta_context: io_interface
- 
    meta_key: subtitle
    meta_field: 
      is_required: false
    key_map: XMP-photoshop:Headline
    meta_context: io_interface
- 
    meta_key: title
    meta_field: 
      is_required: true
      length_max: 4096
      length_min: 1
    key_map: XMP-dc:Title
    meta_context: io_interface
- 
    meta_key: type
    meta_field: 
      is_required: true
    key_map: XMP-dc:Type
    meta_context: io_interface
- 
    meta_key: project type
    meta_field: 
      is_required: true
    key_map: XMP-madek:ProjectType
    meta_context: io_interface
- 
    meta_key: academic year
    meta_field: 
      is_required: false
    key_map: XMP-madek:AcademicYear
    meta_context: io_interface
- 
    meta_key: participating institution
    meta_field: 
      is_required: false
    key_map: XMP-madek:ParticipatingInstitution
    meta_context: io_interface
- 
    meta_key: publisher
    meta_field: 
      is_required: false
    key_map: XMP-madek:Publisher
    meta_context: io_interface
- 
    meta_key: transmission reference
    meta_field: 
      is_required: false
    key_map: XMP-madek:TransmissionReference
    meta_context: io_interface
- 
    meta_key: urn
    meta_field: 
      is_required: false
    key_map: XMP-madek:Urn
    meta_context: io_interface
- 
    meta_key: tags
    meta_field: 
      is_required: false
    key_map: XMP-madek:Tags
    meta_context: io_interface
- 
    meta_key: date created
    meta_field: 
      is_required: false
    key_map: XMP-madek:DateCreated, XMP-photoshop:DateCreated
    meta_context: io_interface
