---
#
#   Uploader
#
- 
    meta_key: title
    meta_field: 
      is_required: true
      description: 
        de_CH: Titel des Medieneintrags
        en_GB: The title of the media entry
      label: 
        de_CH: Titel
        en_GB: Title
      length_max: 255
      length_min: 1
    meta_context: upload
- 
    meta_key: author
    meta_field: 
      description: 
        de_CH: Urheberin oder Urheber des abgebildeten Werkes
        en_GB: Creator of the depicted work
      label: 
        de_CH: Autor/in
        en_GB: Author
    meta_context: upload
- 
    meta_key: portrayed object dates
    meta_field: 
      description: 
        de_CH: Datum der Erstellung des Medieninhalts (z.B. 1878, 1.3.2003 oder Frühlingssemester 2011) - Nicht das Datum, an dem die Datei entstanden ist.
        en_GB: Date of creation of media content (e.g. 1878, 1.3.2003 or Spring semester 2011) - not of the media file.
      label: 
        de_CH: Datum
        en_GB: Date Created
      length_max: 255
    meta_context: upload
- 
    meta_key: keywords
    meta_field: 
      description: 
        de_CH: Schlagworte zu Inhalt und Motiv des Medieneintrags
        en_GB: Keywords describing the media entry content
      label: 
        de_CH: Inhalt und Motiv
        en_GB: Content Keywords
    meta_context: upload
- 
    meta_key: copyright notice
    meta_field: 
      is_required: true
      description: 
        de_CH: Besitzer/in der Nutzungs- und Verwertungsrechte
        en_GB: Copyright owner
      label: 
        de_CH: Copyright
        en_GB: Copyright
      length_max: 255
      length_min: 1
    meta_context: upload
- 
    meta_key: copyright status
    meta_field: 
      description: 
        de_CH: Ist das Werk urheberrechtlich geschützt oder gemeinfrei?
        en_GB:
      label: 
        de_CH: Copyright-Status
        en_GB: Copyright Status
      hint:
        de_CH: Urheberrechtlich geschützt oder gemeinfrei
        en_GB: Urheberrechtlich geschützt oder gemeinfrei
    meta_context: upload
- 
    meta_key: copyright usage
    meta_field: 
      label: 
        de_CH: Nutzungsbedingungen
        en_GB: Usage conditions
    meta_context: upload
- 
    meta_key: copyright url
    meta_field: 
      description: 
        de_CH: Internetlink zur detaillierten Beschreibung der Nutzungsbedingungen wie z.B. Lizenztexte und Publikationsdisclaimer.
        en_GB: Copyright URL for detailed description of usage rights of the work.
      label: 
        de_CH: URL für Copyright-Informationen
        en_GB: Copyright-Info URL
    meta_context: upload