--- 
#
#   Detail view media entry
#   Kurzinfo (blue box) -> MAdeK Core
#
- 
    meta_key: title
    meta_field: 
      is_required: true
      description: 
        de_CH: Titel des Medieneintrags
        en_GB: The title of the media entry
      label: 
        de_CH: Titel
        en_GB: Title
      length_max: 255
      length_min: 1
    meta_context: core
- 
    meta_key: author
    meta_field: 
      is_required: true
      description: 
        de_CH: Urheber/in des abgebildeten Werkes
        en_GB: Creator of the depicted work
      label: 
        de_CH: Autor/in
        en_GB: Author
    meta_context: core
- 
    meta_key: portrayed object dates
    meta_field: 
      is_required: true
      description: 
        de_CH: Datum der Erstellung des Medieninhalts (z.B. 1878, 1.3.2003 oder Frühlingssemester 2011) - Nicht das Datum, an dem die Datei entstanden ist.
        en_GB: Date of creation of media content (e.g. 1878, 1.3.2003 or Spring semester 2011) - not of the media file.
      label: 
        de_CH: Datum
        en_GB: Date Created
      length_max: 255
    meta_context: core
- 
    meta_key: keywords
    meta_field: 
      description: 
        de_CH: Schlagworte zu Inhalt und Motiv des Medieneintrags
        en_GB: Keywords describing the media entry content
      label: 
        de_CH: Inhalt und Motiv
        en_GB: Content Keywords
    meta_context: core
- 
    meta_key: copyright notice
    meta_field: 
      description: 
        de_CH: Besitzer/in der Nutzungs- und Verwertungsrechte
        en_GB: Copyright owner
      label: 
        de_CH: Copyright
        en_GB: Copyright
      length_max: 255
      length_min: 1
    meta_context: core
- 
    meta_key: uploaded by
    meta_field:
      label: 
        de_CH: Hochgeladen von
        en_GB: Uploaded by
    meta_context: core
- 
    meta_key: uploaded at
    meta_field:
      label: 
        de_CH: Hochgeladen am
        en_GB: Uploaded at
    meta_context: core
