all: -r features --tags=~@slow --tags=~@upcoming --format progress --format rerun --out tmp/rerun.txt --format junit --out tmp/junit --format html --out tmp/html/cucumber_all.html
slow: -r features --tags=@slow --format progress --format junit --out tmp/junit --format html --out tmp/html/cucumber_slow.html
default: -r features --tags=~@slow --tags=~@upcoming --format progress --format rerun --out tmp/rerun.txt --format junit --out tmp/junit --format html --out tmp/html/cucumber.html -e 'features/examples' features
rerun: "-r features @tmp/rerun.txt --format progress"
profiling: -r features --no-color  --format pretty --format usage --out tmp/cucumber_usage.txt --format rerun --out tmp/rerun.txt
