all: -r features --tags=~@upcoming --format progress --format rerun --out tmp/rerun.txt --format junit --out tmp/junit --format html --out tmp/html/cucumber_all.html
default: -r features --tags=~@upcoming --format progress --format rerun --out tmp/rerun.txt --format junit --out tmp/junit --format html --out tmp/html/cucumber_all.html
rerun: "-r features @tmp/rerun.txt --format progress"
profiling: -r features --no-color  --format pretty --format usage --out tmp/cucumber_usage.txt --format rerun --out tmp/rerun.txt
