<% jruby = defined?(JRUBY_VERSION)  %>

<% if jruby == "constant" %>
development:
  adapter: jdbcpostgresql
  host: localhost
  database: madek_dev
  encoding: utf8
  username: postgres
  password: 

test:
  adapter: jdbcpostgresql
  host: localhost
  encoding: utf8
  database: madek_test
  username: postgres
  password: 

personas:
  adapter: jdbcpostgresql
  host: localhost
  database: madek_personas
  encoding: utf8
  username: postgres
  password: 
<% else %>

pg: &pg
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  host: localhost
  password:
  pool: 5
 
my: &my
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost
  password:
  pool: 5

default: &default
  <<: *pg

development: 
  <<: *default
  database: madek_dev
test: 
  <<: *default
  database: madek_test
personas: 
  <<: *default
  database: madek_personas
production:
  <<: *default
  database: madek_prod


my_development: 
  <<: *my 
  database: madek_dev
my_test: 
  <<: *my 
  database: madek_test
my_personas: 
  <<: *my
  database: madek_personas
my_production: 
  <<: *my 
  database: madek_prod


pg_development: 
  <<: *pg 
  database: madek_dev
pg_test: 
  <<: *pg 
  database: madek_test
pg_personas: 
  <<: *pg
  database: madek_personas
pg_production: 
  <<: *pg 
  database: madek_prod
<% end %>
