pg: &pg
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  host: localhost
  password:
  
my: &my
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost
  password:

default: &default
  <<: *my
  pool: 5


development: 
  <<: *default
  database: madek_dev

test: 
  <<: *default
  database: madek_test

production:
  <<: *default
  database: madek_prod


