test: 
  adapter: postgresql
  database: madek_test
  encoding: utf8
  username: jenkins
  password: jenkins

personas: 
  adapter: postgresql
  database: madek_personas
  encoding: utf8
  username: jenkins
  password: jenkins
